config/routes.rb
Rails.application.routes.draw do
  resources :formularios do
    collection do
      get :search
    end
    member do
      get :download
      get :download_later
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/formulario.rb
class Formulario < ApplicationRecord

    validates :title, :cover_letter, :categoria, :presence => true

    ROUTE_PATH = "#{Rails.root}/public/Archivos/procesos/"
    REFERENCES_CATEGORY = {
      "avaluo" => "avalúo",
      "compra" => "compra",
      "captacion" => "captación",
      "credito" => "crédito"
    }

    before_create :convert_category
    before_save :convert_category

    scope :by_category, -> (value) {where(categoria: value)}
    def convert_category
      self.categoria.downcase
    end

    def self.get_name_folder
      folders = Dir[ "#{ROUTE_PATH}**" ].reject{|folder| !File.directory?(folder)}
      return [] if !folders.present?
      folders.map{|folder| File.basename(folder).capitalize}
    end

    def self.return_true_files directory
      return [] if directory.nil?
      directory.reject{|file| File.directory?(file)}
    end

    def self.search(search=nil)

      return Formulario.all if search.nil?
      Formulario.by_category(search)

      #return return_true_files(Dir["#{ROUTE_PATH}/**/**"]) if !search.present?
      #route_path = "#{ROUTE_PATH}#{search.downcase}"
      #File.directory?(route_path) ? return_true_files(Dir["#{route_path}/**"]) : return_true_files(Dir["#{ROUTE_PATH}/**/**"])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def redirect_later(url, msg, delay = 5)
    flash[:redirect_later] = {
        url: url,
        delay: delay,
        msg: msg,
    }
  end

end

app/controllers/formularios_controller.rb
require 'fileutils'
class FormulariosController < ApplicationController
  before_action :set_formulario, only: [:show, :edit, :update, :destroy, :download, :download_later]

  # GET /formularios
  # GET /formularios.json
  def index
    @formularios = Formulario.search
    @select_options = Formulario.get_name_folder
  end

  # GET /formularios/1
  # GET /formularios/1.json
  def show
    respond_to do |format|
      format.html
      format.js
    end
    extension = @formulario.title.split('.')
    #send_file Rails.root.join('public','Archivos','procesos','avaluo', @formulario.title),
    #:type=>"application/#{extension[1]}", :x_sendfile=>true
  end

  def download
    extension = File.extname(@formulario.title)
    category = Formulario::REFERENCES_CATEGORY[@formulario.categoria]

    send_file(Rails.root.join(Formulario::ROUTE_PATH, category, @formulario.title),
              :type=>"application/#{extension}", :x_sendfile=>true)

  end

  def download_later
    redirect_later download_formulario(@formulario), "Download starts in %d seconds."
  end

  # GET /formularios/new
  def new
    @formulario = Formulario.new
    @select_options = Formulario.get_name_folder
  end

  # GET /formularios/1/edit
  def edit
  end

  # POST /formularios
  # POST /formularios.json
  def create
    @formulario = Formulario.new(formulario_params)
    if params[:formulario][:categoria].present?
      category = Formulario::REFERENCES_CATEGORY[params[:formulario][:categoria]]
      uploaded_io= params[:formulario][:title].tempfile
      #File.open(Rails.root.join("#{Formulario::ROUTE_PATH}",category, uploaded_io.original_filename), 'wb') do |file|
      #  file.write(uploaded_io)
      #end
      file = File.join("#{Formulario::ROUTE_PATH}",category, params[:formulario][:title].original_filename)
      FileUtils.cp uploaded_io.path, file
      #FileUtils.rm file
      @formulario.title= params[:formulario][:title].original_filename
    end
    respond_to do |format|
      if @formulario.save
        format.html { redirect_to @formulario, notice: 'Formulario was successfully created.' }
        format.json { render :show, status: :created, location: @formulario }
      else
        format.html { render :new, alert: "An error has ocurred" }
        format.json { render json: @formulario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formularios/1
  # PATCH/PUT /formularios/1.json
  def update
    respond_to do |format|
      if @formulario.update(formulario_params)
        format.html { redirect_to @formulario, notice: 'Formulario was successfully updated.' }
        format.json { render :show, status: :ok, location: @formulario }
      else
        format.html { render :edit }
        format.json { render json: @formulario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formularios/1
  # DELETE /formularios/1.json
  def destroy
    category = Formulario::REFERENCES_CATEGORY[@formulario.categoria]
    file = File.join("#{Formulario::ROUTE_PATH}",category, @formulario.title)
    FileUtils.rm file
    @formulario.destroy
    respond_to do |format|
      puts "----------> #{formularios_url}"
      format.html { redirect_to formularios_url, notice: 'Formulario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @formularios = Formulario.search(params[:search])
    @select_options = Formulario.get_name_folder
    puts ">>>>>>> #{@formularios}"
    respond_to :js
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formulario
      @formulario = Formulario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def formulario_params
      params.require(:formulario).permit(:id, :title, :cover_letter, :categoria)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def redirect_later_tag
    return nil unless flash.key?(:redirect_later)

    url = flash[:redirect_later][:url]
    delay = flash[:redirect_later]["delay"]
    flash.now[:notice] = flash[:redirect_later]["msg"] % [delay]

    flash.delete(:redirect_later)

    tag("meta",
        "http-equiv" => "refresh",
        content: "#{delay}; URL=#{url}")
  end

end

app/helpers/formularios_helper.rb
require "i18n"
module FormulariosHelper
  def get_name_folder
    folders = Dir[ "#{Formulario::ROUTE_PATH}**" ].reject{|folder| !File.directory?(folder)}
    return [] if !folders.present?
    folder_names = folders.map{|folder| File.basename(folder).capitalize}
    array_example = []
    folder_names.each{|folder| array_example << [folder, I18n.transliterate(folder.downcase)]}
    array_example
  end
end

app/views/formularios/_form.html.erb
<%= form_with(model: formulario, local: true, :multipart => true) do |form| %>
  <% if formulario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(formulario.errors.count, "error") %> prohibited this formulario from being saved:</h2>

      <ul>
      <% formulario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.file_field :title, :required => true %>
  </div>

  <div class="field">
    <%= form.label :cover_letter %>
    <%= form.text_area :cover_letter, :required => true %>
  </div>

  <div class="field">
    <%= form.label :categoria %>
    <%= form.select :categoria, get_name_folder, id: :formulario_categoria, include_blank: 'Please choose', :required => true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/formularios/_index.html.erb
<table class="files_tbody_content bordered" width="100%" >
<thead>
<tr>
  <th>Cover letter</th>
  <th>Title</th>
  <th colspan="3"></th>
</tr>
</thead>
  <tbody >
  <% @formularios.each do |formulario| %>
    <tr>
      <td><%= File.basename(formulario.title) %></td>
      <td><%= File.basename(formulario.cover_letter) %></td>
      <td>
        <%= link_to 'Ver', formulario_url(formulario),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: "btn btn-primary btn2" } %>

      </td>
      <!-- <td><%= link_to 'Edit', edit_formulario_path(formulario) %></td>
      <td><%= link_to 'Destroy', formulario, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
    </tr>
  <% end %>
  </tbody>
</table>
<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

app/views/formularios/_show.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel"><%= @formulario.title %></h4>
</div>
<div class="modal-body">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @formulario.title %>
  </p>

  <p>
    <strong>Cover letter:</strong>
    <%= @formulario.cover_letter %>
  </p>
</div>
<div class="modal-footer">
  <%# link_to 'Edit', edit_formulario_path(@formulario) %> |
  <%= link_to 'Descargar', download_formulario_url(@formulario) %> |
  <%= link_to 'Back', formularios_path %>
</div>

app/views/formularios/edit.html.erb
<h1>Editing Formulario</h1>

<%= render 'form', formulario: @formulario %>

<%= link_to 'Show', @formulario %> |
<%= link_to 'Back', formularios_path %>

app/views/formularios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Formularios</h1>

<div class="form-group " width="100%">

<select id="categories" class = "search_files">
    <%= @select_options.each do |option| %>
    <option><%= option %></option>
    <% end %>
</select>
</div>

  <%= render 'index' %>



<br>

<%= link_to 'New Formulario', new_formulario_path %>

<script type="text/javascript">

</script>

app/views/formularios/new.html.erb
<h1>New Formulario</h1>

<%= render 'form', formulario: @formulario %>

<%= link_to 'Back', formularios_path %>

app/views/formularios/search.js.erb
$(".files_tbody_content").html("<%= escape_javascript render(:partial => 'formularios/index', :locals => { :formularios => @formularios }) %>");

app/views/formularios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @formulario.title %>
</p>

<p>
  <strong>Cover letter:</strong>
  <%= @formulario.cover_letter %>
</p>

<%# link_to 'Edit', edit_formulario_path(@formulario) %> |
<%= link_to 'Descargar', download_formulario_url(@formulario) %> |
<%= link_to 'Back', formularios_path %>

app/views/formularios/show.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'show') %>");
$("#modal-window").modal();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Descargas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
    <%= redirect_later_tag %>
  </body>
</html>